# Config file for automatic testing at travis-ci.org

os: osx

language: python

python:
  - "3.6"
  - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install coveralls

# command to run tests, e.g. python setup.py test
#script: python setup.py test
script:
  - coverage run --source=twodolib setup.py test
  - coverage report -m
after_success:
  - coveralls
